name: Wow Guides
title: How to play | Guides for Wow
description: How to play guides for World of Warcraft.
tags:
  - blog
  - Guides
  - Rotation
  - how to
  - World of Warcraft
  - Fire Mage
show_hero: true
menu:
  - title: Home
    url: /
  - title: About Tymazen
    url: /about
  - title: Other Resources
    url: /other_resources
  - title: Acknowledgements
    url: /Acknowledgements
email: youremail@test.com
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
